DEEPL_LANGUAGES = [
("Arabic (AR)", "AR"),
("Bulgarian (BG)", "BG"),
("Czech (CS)", "CS"),
("Danish (DA)", "DA"),
("German (DE)", "DE"),
("Greek (EL)", "EL"),
("English (EN)", "EN"),
("English (British) (EN-GB)", "EN-GB"),
("English (American) (EN-US)", "EN-US"),
("Spanish (ES)", "ES"),
("Estonian (ET)", "ET"),
("Finnish (FI)", "FI"),
("French (FR)", "FR"),
("Hungarian (HU)", "HU"),
("Indonesian (ID)", "ID"),
("Italian (IT)", "IT"),
("Japanese (JA)", "JA"),
("Korean (KO)", "KO"),
("Lithuanian (LT)", "LT"),
("Latvian (LV)", "LV"),
("Norwegian Bokmål (NB)", "NB"),
("Dutch (NL)", "NL"),
("Polish (PL)", "PL"),
("Portuguese (PT)", "PT"),
("Portuguese (Brazilian) (PT-BR)", "PT-BR"),
("Portuguese (European) (PT-PT)", "PT-PT"),
("Romanian (RO)", "RO"),
("Russian (RU)", "RU"),
("Slovak (SK)", "SK"),
("Slovenian (SL)", "SL"),
("Swedish (SV)", "SV"),
("Turkish (TR)", "TR"),
("Ukrainian (UK)", "UK"),
("Chinese (unspecified variant) (ZH)", "ZH"),
("Chinese (simplified) (ZH-HANS)", "ZH-HANS"),
("Chinese (traditional) (ZH-HANT)", "ZH-HANT")
]

GOOGLE_LANGUAGES = [
("Abkhaz (ab)", "ab"),
("Acehnese (ace)", "ace"),
("Acholi (ach)", "ach"),
("Afrikaans (af)", "af"),
("Albanian (sq)", "sq"),
("Alur (alz)", "alz"),
("Amharic (am)", "am"),
("Arabic (ar)", "ar"),
("Armenian (hy)", "hy"),
("Assamese (as)", "as"),
("Awadhi (awa)", "awa"),
("Aymara (ay)", "ay"),
("Azerbaijani (az)", "az"),
("Balinese (ban)", "ban"),
("Bambara (bm)", "bm"),
("Bashkir (ba)", "ba"),
("Basque (eu)", "eu"),
("Batak Karo (btx)", "btx"),
("Batak Simalungun (bts)", "bts"),
("Batak Toba (bbc)", "bbc"),
("Belarusian (be)", "be"),
("Bemba (bem)", "bem"),
("Bengali (bn)", "bn"),
("Betawi (bew)", "bew"),
("Bhojpuri (bho)", "bho"),
("Bikol (bik)", "bik"),
("Bosnian (bs)", "bs"),
("Breton (br)", "br"),
("Bulgarian (bg)", "bg"),
("Buryat (bua)", "bua"),
("Cantonese (yue)", "yue"),
("Catalan (ca)", "ca"),
("Cebuano (ceb)", "ceb"),
("Chichewa (Nyanja) (ny)", "ny"),
("Chinese (Simplified)", "zh-CN"),
("Chinese (Traditional)", "zh-TW"),
("Chuvash (cv)", "cv"),
("Corsican (co)", "co"),
("Crimean Tatar (crh)", "crh"),
("Croatian (hr)", "hr"),
("Czech (cs)", "cs"),
("Danish (da)", "da"),
("Dinka (din)", "din"),
("Divehi (dv)", "dv"),
("Dogri (doi)", "doi"),
("Dombe (dov)", "dov"),
("Dutch (nl)", "nl"),
("Dzongkha (dz)", "dz"),
("English (en)", "en"),
("Esperanto (eo)", "eo"),
("Estonian (et)", "et"),
("Ewe (ee)", "ee"),
("Fijian (fj)", "fj"),
("Filipino (Tagalog)", "fil"), # using "fil" from "fil or tl"
("Finnish (fi)", "fi"),
("French (fr)", "fr"),
("French (French)", "fr-FR"),
("French (Canadian)", "fr-CA"),
("Frisian (fy)", "fy"),
("Fulfulde (ff)", "ff"),
("Ga (gaa)", "gaa"),
("Galician (gl)", "gl"),
("Ganda (Luganda) (lg)", "lg"),
("Georgian (ka)", "ka"),
("German (de)", "de"),
("Greek (el)", "el"),
("Guarani (gn)", "gn"),
("Gujarati (gu)", "gu"),
("Haitian Creole (ht)", "ht"),
("Hakha Chin (cnh)", "cnh"),
("Hausa (ha)", "ha"),
("Hawaiian (haw)", "haw"),
("Hebrew (he)", "he"), # using "he" from "iw or he"
("Hiligaynon (hil)", "hil"),
("Hindi (hi)", "hi"),
("Hmong (hmn)", "hmn"),
("Hungarian (hu)", "hu"),
("Hunsrik (hrx)", "hrx"),
("Icelandic (is)", "is"),
("Igbo (ig)", "ig"),
("Iloko (ilo)", "ilo"),
("Indonesian (id)", "id"),
("Irish (ga)", "ga"),
("Italian (it)", "it"),
("Japanese (ja)", "ja"),
("Javanese (jw)", "jw"), # choosing "jw" over "jv"
("Kannada (kn)", "kn"),
("Kapampangan (pam)", "pam"),
("Kazakh (kk)", "kk"),
("Khmer (km)", "km"),
("Kiga (cgg)", "cgg"),
("Kinyarwanda (rw)", "rw"),
("Kituba (ktu)", "ktu"),
("Konkani (gom)", "gom"),
("Korean (ko)", "ko"),
("Krio (kri)", "kri"),
("Kurdish (Kurmanji) (ku)", "ku"),
("Kurdish (Sorani) (ckb)", "ckb"),
("Kyrgyz (ky)", "ky"),
("Lao (lo)", "lo"),
("Latgalian (ltg)", "ltg"),
("Latin (la)", "la"),
("Latvian (lv)", "lv"),
("Ligurian (lij)", "lij"),
("Limburgan (li)", "li"),
("Lingala (ln)", "ln"),
("Lithuanian (lt)", "lt"),
("Lombard (lmo)", "lmo"),
("Luo (luo)", "luo"),
("Luxembourgish (lb)", "lb"),
("Macedonian (mk)", "mk"),
("Maithili (mai)", "mai"),
("Makassar (mak)", "mak"),
("Malagasy (mg)", "mg"),
("Malay (ms)", "ms"),
("Malay (Jawi) (ms-Arab)", "ms-Arab"),
("Malayalam (ml)", "ml"),
("Maltese (mt)", "mt"),
("Maori (mi)", "mi"),
("Marathi (mr)", "mr"),
("Meadow Mari (chm)", "chm"),
("Meiteilon (Manipuri) (mni-Mtei)", "mni-Mtei"),
("Minang (min)", "min"),
("Mizo (lus)", "lus"),
("Mongolian (mn)", "mn"),
("Myanmar (Burmese) (my)", "my"),
("Ndebele (South) (nr)", "nr"),
("Nepalbhasa (Newari) (new)", "new"),
("Nepali (ne)", "ne"),
("Northern Sotho (Sepedi) (nso)", "nso"),
("Norwegian (no)", "no"),
("Nuer (nus)", "nus"),
("Occitan (oc)", "oc"),
("Odia (Oriya) (or)", "or"),
("Oromo (om)", "om"),
("Pangasinan (pag)", "pag"),
("Papiamento (pap)", "pap"),
("Pashto (ps)", "ps"),
("Persian (fa)", "fa"),
("Polish (pl)", "pl"),
("Portuguese (pt)", "pt"),
("Portuguese (Portugal) (pt-PT)", "pt-PT"),
("Portuguese (Brazil) (pt-BR)", "pt-BR"),
("Punjabi (pa)", "pa"),
("Punjabi (Shahmukhi) (pa-Arab)", "pa-Arab"),
("Quechua (qu)", "qu"),
("Romani (rom)", "rom"),
("Romanian (ro)", "ro"),
("Rundi (rn)", "rn"),
("Russian (ru)", "ru"),
("Samoan (sm)", "sm"),
("Sango (sg)", "sg"),
("Sanskrit (sa)", "sa"),
("Scots Gaelic (gd)", "gd"),
("Serbian (sr)", "sr"),
("Sesotho (st)", "st"),
("Seychellois Creole (crs)", "crs"),
("Shan (shn)", "shn"),
("Shona (sn)", "sn"),
("Sicilian (scn)", "scn"),
("Silesian (szl)", "szl"),
("Sindhi (sd)", "sd"),
("Sinhala (Sinhalese) (si)", "si"),
("Slovak (sk)", "sk"),
("Slovenian (sl)", "sl"),
("Somali (so)", "so"),
("Spanish (es)", "es"),
("Sundanese (su)", "su"),
("Swahili (sw)", "sw"),
("Swati (ss)", "ss"),
("Swedish (sv)", "sv"),
("Tajik (tg)", "tg"),
("Tamil (ta)", "ta"),
("Tatar (tt)", "tt"),
("Telugu (te)", "te"),
("Tetum (tet)", "tet"),
("Thai (th)", "th"),
("Tigrinya (ti)", "ti"),
("Tsonga (ts)", "ts"),
("Tswana (tn)", "tn"),
("Turkish (tr)", "tr"),
("Turkmen (tk)", "tk"),
("Twi (Akan) (ak)", "ak"),
("Ukrainian (uk)", "uk"),
("Urdu (ur)", "ur"),
("Uyghur (ug)", "ug"),
("Uzbek (uz)", "uz"),
("Vietnamese (vi)", "vi"),
("Welsh (cy)", "cy"),
("Xhosa (xh)", "xh"),
("Yiddish (yi)", "yi"),
("Yoruba (yo)", "yo"),
("Yucatec Maya (yua)", "yua"),
("Zulu (zu)", "zu")
]